/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Classes.ContaCorrenteComum;
import Classes.ContaCorrenteLimitada;
import Classes.ContaPoupanca;
import Classes.Transacao;
import Hibernate.ClasseDAO;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author FábioJunior
 */
public class SaquesBanco extends javax.swing.JFrame {

    Transacao ex = new Transacao();

    Object cliente = new Object();
    String t = "";

    public SaquesBanco() {

    }

    public void retira(Object cliente, double valor) {
        if (cliente instanceof ContaPoupanca) {
            ContaPoupanca cp = new ContaPoupanca();
            cp = (ContaPoupanca) cliente;
            cp.retirada(cp, valor);
        }
        if (cliente instanceof ContaCorrenteComum) {
            ContaCorrenteComum ccc = new ContaCorrenteComum();
            ccc = (ContaCorrenteComum) cliente;
            ccc.retirada(ccc, valor);
        }
        if (cliente instanceof ContaCorrenteLimitada) {
            ContaCorrenteLimitada ccl = new ContaCorrenteLimitada();
            ccl = (ContaCorrenteLimitada) cliente;
            ccl.retirada(ccl, valor);
        }
    }

    

    /**
     * Creates new form SaquesBanco
     */
    public SaquesBanco(Object cli) {
        initComponents();
        cliente = cli;

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSacar300 = new javax.swing.JButton();
        btnSacar100 = new javax.swing.JButton();
        btnSacar50 = new javax.swing.JButton();
        btnSacar500 = new javax.swing.JButton();
        btnSacar700 = new javax.swing.JButton();
        btnSacarOutro = new javax.swing.JButton();
        bntExtrato = new javax.swing.JButton();
        varSaldo = new javax.swing.JButton();
        btnExPeriodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        btnSacar300.setBackground(new java.awt.Color(0, 51, 153));
        btnSacar300.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSacar300.setForeground(new java.awt.Color(255, 255, 255));
        btnSacar300.setText("Sacar R$300");
        btnSacar300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacar300ActionPerformed(evt);
            }
        });

        btnSacar100.setBackground(new java.awt.Color(0, 51, 153));
        btnSacar100.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSacar100.setForeground(new java.awt.Color(255, 255, 255));
        btnSacar100.setText("Sacar R$100");
        btnSacar100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacar100ActionPerformed(evt);
            }
        });

        btnSacar50.setBackground(new java.awt.Color(0, 51, 153));
        btnSacar50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSacar50.setForeground(new java.awt.Color(255, 255, 255));
        btnSacar50.setText("Sacar R$50");
        btnSacar50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacar50ActionPerformed(evt);
            }
        });

        btnSacar500.setBackground(new java.awt.Color(0, 51, 153));
        btnSacar500.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSacar500.setForeground(new java.awt.Color(255, 255, 255));
        btnSacar500.setText("Sacar R$500");
        btnSacar500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacar500ActionPerformed(evt);
            }
        });

        btnSacar700.setBackground(new java.awt.Color(0, 51, 153));
        btnSacar700.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSacar700.setForeground(new java.awt.Color(255, 255, 255));
        btnSacar700.setText("Sacar R$700");
        btnSacar700.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacar700ActionPerformed(evt);
            }
        });

        btnSacarOutro.setBackground(new java.awt.Color(0, 51, 153));
        btnSacarOutro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSacarOutro.setForeground(new java.awt.Color(255, 255, 255));
        btnSacarOutro.setText("Sacar Outro Valor");
        btnSacarOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarOutroActionPerformed(evt);
            }
        });

        bntExtrato.setBackground(new java.awt.Color(0, 51, 153));
        bntExtrato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntExtrato.setForeground(new java.awt.Color(255, 255, 255));
        bntExtrato.setText("Extrato");
        bntExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExtratoActionPerformed(evt);
            }
        });

        varSaldo.setBackground(new java.awt.Color(0, 51, 153));
        varSaldo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        varSaldo.setForeground(new java.awt.Color(255, 255, 255));
        varSaldo.setText("Saldo");
        varSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varSaldoActionPerformed(evt);
            }
        });

        btnExPeriodo.setBackground(new java.awt.Color(0, 51, 153));
        btnExPeriodo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExPeriodo.setForeground(new java.awt.Color(255, 255, 255));
        btnExPeriodo.setText("Extrato por Periodo");
        btnExPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExPeriodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSacar50, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSacar100, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSacar300, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSacar500, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSacar700, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSacarOutro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(varSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSacar500, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacar700, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacarOutro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSacar50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacar100, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacar300, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnExPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacar50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacar50ActionPerformed
        retira(cliente, 50);
    }//GEN-LAST:event_btnSacar50ActionPerformed

    private void btnSacar100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacar100ActionPerformed
        retira(cliente, 100);
    }//GEN-LAST:event_btnSacar100ActionPerformed

    private void btnSacar300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacar300ActionPerformed
        retira(cliente, 300);
    }//GEN-LAST:event_btnSacar300ActionPerformed

    private void btnSacar500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacar500ActionPerformed
        retira(cliente, 500);
    }//GEN-LAST:event_btnSacar500ActionPerformed

    private void btnSacar700ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacar700ActionPerformed
        retira(cliente, 700);
    }//GEN-LAST:event_btnSacar700ActionPerformed

    private void bntExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExtratoActionPerformed
        Transacao ex = new Transacao();
        ClasseDAO cd = new ClasseDAO();
        ArrayList<Transacao> ext = new ArrayList<>();
        if (cliente instanceof ContaPoupanca) {
            ContaPoupanca cp = new ContaPoupanca();
            cp = (ContaPoupanca) cliente;
            cp = (ContaPoupanca) cd.procuraConta(cliente, cp.getNumero(), cp.getAgencia());
            new TelaExtrato("" + cp.getExtrato()).setVisible(true);
        }
        if (cliente instanceof ContaCorrenteComum) {
            ContaCorrenteComum ccc = new ContaCorrenteComum();
            ccc = (ContaCorrenteComum) cliente;
            ccc = (ContaCorrenteComum) cd.procuraConta(cliente, ccc.getNumero(), ccc.getAgencia());
            new TelaExtrato("" + ccc.getExtrato()).setVisible(true);
        }
        if (cliente instanceof ContaCorrenteLimitada) {
            ContaCorrenteLimitada ccl = new ContaCorrenteLimitada();
            ccl = (ContaCorrenteLimitada) cliente;
            ccl = (ContaCorrenteLimitada) cd.procuraConta(cliente, ccl.getNumero(), ccl.getAgencia());
            new TelaExtrato("" + ccl.getExtrato()).setVisible(true);
        }
    }//GEN-LAST:event_bntExtratoActionPerformed

    private void varSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varSaldoActionPerformed
        ClasseDAO cd = new ClasseDAO();
        if (cliente instanceof ContaPoupanca) {

            ContaPoupanca cp = new ContaPoupanca();
            cp = (ContaPoupanca) cliente;
            cp = (ContaPoupanca) cd.procuraConta(cp, cp.getNumero(), cp.getAgencia());
            JOptionPane.showMessageDialog(null, "Seu Saldo é: R$" + cp.getSaldo());
        } else if (cliente instanceof ContaCorrenteComum) {
            ContaCorrenteComum ccc = new ContaCorrenteComum();
            ccc = (ContaCorrenteComum) cliente;
            ccc = (ContaCorrenteComum) cd.procuraConta(ccc, ccc.getNumero(), ccc.getAgencia());
            JOptionPane.showMessageDialog(null, "Seu Saldo é: R$" + ccc.getSaldo());
        } else if (cliente instanceof ContaCorrenteLimitada) {
            ContaCorrenteLimitada ccl = new ContaCorrenteLimitada();
            ccl = (ContaCorrenteLimitada) cliente;
            ccl = (ContaCorrenteLimitada) cd.procuraConta(ccl, ccl.getNumero(), ccl.getAgencia());
            JOptionPane.showMessageDialog(null, "Seu Saldo é: R$" + ccl.getSaldo());
        }
    }//GEN-LAST:event_varSaldoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new TelaCaixa().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btnSacarOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarOutroActionPerformed
        double valor = Double.valueOf(JOptionPane.showInputDialog(null, "Digite o Valor"));
        retira(cliente, valor);
    }//GEN-LAST:event_btnSacarOutroActionPerformed

    private void btnExPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExPeriodoActionPerformed
        Transacao tx = new Transacao();
        Date ini, fim;
        ini = ex.converteData(JOptionPane.showInputDialog("Digite a Data inicial: EX: DD/MM/AAAA"));
        fim = ex.converteData(JOptionPane.showInputDialog("Digite a Data Final: EX: DD/MM/AAAA"));
        new TelaExtrato(tx.imprimeExtratoPeriodo(cliente, ini, fim)).setVisible(true);
    }//GEN-LAST:event_btnExPeriodoActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaquesBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaquesBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaquesBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaquesBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente c = ;
                c = cliente.
                new SaquesBanco().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntExtrato;
    private javax.swing.JButton btnExPeriodo;
    private javax.swing.JButton btnSacar100;
    private javax.swing.JButton btnSacar300;
    private javax.swing.JButton btnSacar50;
    private javax.swing.JButton btnSacar500;
    private javax.swing.JButton btnSacar700;
    private javax.swing.JButton btnSacarOutro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton varSaldo;
    // End of variables declaration//GEN-END:variables
}
